name: Events Demo 1
on:
    # we want this event to fire of when pull requests
    # are opened
    pull_request:
        types: 
            - opened
    # we also want to add a manual event
    workflow_dispatch:
    # event filters
    push:
        branches:
            - main # only pushes to the main branch will trigger this workflow
        # you can also filter by paths
        # you want to run a workflow if files change in 
        # specific path
        # you can use path-ignore which does the opposite
        # paths: 
        paths-ignore:
            - '.github/workflows/*'
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Output event data
              run: echo "${{ toJson(github.event) }}"
            - name: Get code
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Test code
              run: npm run test
            - name: Build code
              run: npm run build
            - name: Deploy project
              run: echo "Deploying..."